#!/usr/bin/node

// Import the 'request' module to make HTTP requests
const request = require('request');

// Get the URL from the command line arguments
const url = process.argv[2];

// Check if a URL is provided
if (!url) {
  console.error('Usage: ./2-statuscode.js <URL>');
  process.exit(1);
}

// Make a GET request to the URL
request(url, (error, response) => {
  if (error) {
    // If an error occurs, print the error
    console.error(error);
  } else {
    // Print the status code
    console.log(`code: ${response.statusCode}`);
  }
});
